# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_gender
#'
#' @noRd
rcpp_gender <- function(text_in) {
    .Call(`_gendercorrectrouting_rcpp_gender`, text_in)
}

